baseURL: https://alahmadiq8.github.io
languageCode: en-us
title: Mohammad's Personal Website

theme: custom
enableGitInfo: true

googleAnalytics: UA-78685008-2

permalinks:
  posts: /:section/:slug
  projects: /:slug
  work: /:section/:slug

# sectionPagesMenu: main
menu:
  main:
    - name: "Writing"
      url: /posts/
      identifier: posts
      weight: 0
    - name: "Projects"
      url: /projects/
      identifier: projects
      weight: 2
    - name: "Freelance"
      url: /work/
      identifier: work
      weight: 1
    - name: "About Me"
      url: '/#about-me'
      identifier: about-me
      weight: 1

params: 
  author: Mohammad Mohammad (Alahmadi)
  description: Mohammad's Personal Website 
  social:
    linkedin: https://www.linkedin.com/in/mohammad91    
    github: https://github.com/AlahmadiQ8
    email: mailto:m91.alahmadi@gmail.com?Subject=[from my site]
    codepen: https://codepen.io/mhd1991
    twitter: https://twitter.com/AlahmadiKU
    devto: https://dev.to/alahmadiq8
  footer: 
    - <strong>© 2018 Mohammad Alahmadi. All Rights Reserved.</strong>
    - > 
      Made with ❤ & ☕ with <a href="https://gohugo.io" target="_blank">Hugo</a>
    - Site source code is hosted at <a href="https://github.com/AlahmadiQ8/hugo-site" target="_blank">Github</a>
