baseURL: https://alahmadiq8.github.io
languageCode: en-us
title: Mohammad's Personal Website

theme: custom
enableGitInfo: true

permalinks:
  posts: /:section/:slug

# sectionPagesMenu: main
menu:
  main:
    - name: "Writing"
      url: /posts/
      identifier: posts
      weight: 0

params: 
  author: Mohammad Mohammad (Alahmadi)
  description: Mohammad's Personal Website 
  social:
    linkedin: https://www.linkedin.com/in/mohammad91    
    github: https://github.com/AlahmadiQ8
    email: mailto:m91.alahmadi@gmail.com?Subject=[from my site]
    codepen: https://codepen.io/mhd1991
    twitter: https://twitter.com/AlahmadiKU
  footer: 
    - <strong>© 2018 Mohammad Alahmadi. All Rights Reserved.</strong>
    - > 
      Made with ❤ & ☕ with <a href="https://gohugo.io" target="_blank">Hugo</a>
    - Site source code is hosted at <a href="https://github.com/AlahmadiQ8/hugo-site" target="_blank">Github</a>
