baseURL: https://alahmadiq8.github.io/
languageCode: en-us
title: Mohammad's Personal Website

theme: custom

params: 
  author: Mohammad Mohammad (Alahmadi)
  description: Mohammad's Personal Website 
  social:
    linkedin: https://www.linkedin.com/in/mohammad91    
    github: https://github.com/AlahmadiQ8
    email: mailto:m91.alahmadi@gmail.com?Subject=[from my site]
    codepen: https://codepen.io/mhd1991
    twitter: https://twitter.com/AlahmadiKU
